### ISSUE TITLE
CachingBAMFileIndex issue

### ISSUE THREAD

**Issue by kpepper** [samtools/htsjdk#1127] opened 2018-05-23 14:49 UTC
### Verify
Can you see anything in the logs? 
No.

The code below is entered when SamReaderFactory.Option.CACHE_FILE_BASED_INDEXES is enabled.

### Subject of the issue
I'm getting some erroneous caching behaviour from the CachingBAMFileIndex.java getQueryResults(final int referenceIndex) method when loading indexed bam files, whereby the following statement:

// If this query is for the same reference index as the last query, return it.
if(mLastReferenceRetrieved!=null && mLastReferenceRetrieved == referenceIndex)
            return mQueriesByReference.get(referenceIndex);

returns null and the code does not attempt to go to disk to load the missing data. It seems that if mLastReferenceRetrieved is for example 2 and there is an entry with a key of 2 in mQueriesByReference (i.e. in the cache), but that key is garbage collected [removed] from the weak hash map (due to there being no current references to it) then if the method is called later with a referenceIndex input arg of 2, null gets returned instead of reloading the cache [i.e. falling through to the next code section]. Hence the data for that reference section becomes unfetchable and cannot be loaded, unless another reference sequence is selected before trying again. 

The problem seems to be that mLastReferenceRetrieved and mQueriesByReference get out of sync.

CachingBAMFileIndex is used by default for CRAM file loading (from CRAMFileReader), but I haven't been able to replicate the behaviour for that. However, this was using significantly smaller files so it may still be an issue with bigger ones.

This bug seems to show up most readily under memory intensive conditions with bigger bam/fasta files presumably where garbage collection is happening more often.

### Your environment
OSX, Ubuntu

**Comment by kpepper** [comment] 2018-06-04 10:37
Hi **@cmnbroad**, any chance of looking into this as it's proving a bit of a headache? It may be a fairly simple fix to getQueryResults. Thanks.

**Comment by lbergelson** [comment] 2018-06-06 21:27
We should definitely take a look at this.  Sounds like a nasty bug.  I wonder why we haven't noticed it ourselves.

**Comment by lbergelson** [comment] 2018-06-06 21:53
Interesting... @kpepper do you only see this on references with many contigs?  If my understanding of how WeakHashMap operates, it seems like it will remove elements when the key is no longer referenced anywhere.  However, the keys in this case are small integers, which are interned by some mechanism in jvm, so if my suspicion is correct, most keys will never go out of scope...  That would mean that the hashmap may never release elements for low number contigs, which is why we wouldn't see this on most human sequence data.  It's also a memory leak if we're expecting to release index data from memory.  

It also seems like this class is also only intending on actually keeping a single element in the cache at a time as well, because of the weird semantics around integer interning and boxing.

**Comment by kpepper** [comment] 2018-06-07 09:19
**@lbergelson** Thanks, for getting back on this.

Certainly there were a lot of contigs, off the top of my head, 400+.  I haven't seen this behaviour on simpler scenarios with less contigs / smaller files. 

I've temporarily switched the caching off for bams. However, _I think_ crams always use it regardless of the caching property. I also had one report of getting an "Iteration in progress" exception with the caching turned off for the same file set, which I will need to look into.

**Comment by lbergelson** [comment] 2018-06-21 17:46
@kpepper I believe that I've reproduced this issue in a test, and it matches my understanding of the problem.

```
    @Test
    public void testCachingBamFileIndextest() throws IOException {

        //create a bam / index with over 127 contigs
        List<SAMSequenceRecord> contigs = IntStream.range(1, 200)
                .mapToObj(i -> new SAMSequenceRecord(String.valueOf(i), 1000))
                .collect(Collectors.toList());
        final SAMSequenceDictionary dict = new SAMSequenceDictionary(contigs);
        final SAMFileHeader header = new SAMFileHeader(dict);
        header.setSortOrder(SAMFileHeader.SortOrder.coordinate);

        final SAMFileWriterFactory writerFactory = new SAMFileWriterFactory().setCreateIndex(true);
        final File outBam = File.createTempFile("tmp", ".bam");
        try(final SAMFileWriter writer = writerFactory.makeWriter(header, true, outBam, null)){
            IntStream.range(1,200).mapToObj(i -> {
                final SAMRecord record = new SAMRecord(header);
                record.setReadName("name" + i);
                record.setReferenceName(String.valueOf(i));
                record.setReadUnmappedFlag(false);
                record.setAlignmentStart(1);
                record.setCigarString("20M");
                return record;
            }).forEach(writer::addAlignment);
        }

        final File indexFile = new File(outBam.getParent(),IOUtil.basename(outBam) + BAMIndex.BAMIndexSuffix);
        final CachingBAMFileIndex index = new CachingBAMFileIndex(indexFile, dict);

        //loading contig 1 always succeeds even after GC because the jvm interns Integer objects with values -128 to 127
        Assert.assertNotNull(index.getQueryResults(1));
        System.gc();
        Assert.assertNotNull(index.getQueryResults(1));

       // contig 128 is garbage collected and can't be located again
       // due to a bug it fails to reload from the file
        Assert.assertNotNull(index.getQueryResults(128));
        System.gc();
        Assert.assertNotNull(index.getQueryResults(128));
    }
```

This was a really interesting bug.  I have a fix which is to just get rid of the `WeakHashMap` and just keep the last seen index data in memory.  That's the only data that was actually retrievable, but due to the weird interaction between `Integer` and `WeakHashMap` we were storing and never releasing a lot of extra information.  So this will fix this bug as well as a nasty memory leak.

**Comment by kpepper** [comment] 2018-06-22 08:38
Hi **@lbergelson**. Yes, that solution sounds good to me. Thanks.

**Closed** 2018-06-25 20:09 UTC
