### ISSUE TITLE
Header lines with same key are lost when parsing VCF.

### ISSUE THREAD

**Issue by evolvedmicrobe** [samtools/htsjdk#43] opened 2014-06-19 20:26 UTC
Consider a VCF file with the following two lines in the header:

    ##GATKCommandLine=<ID=ExtractConsensusSites, ....
    ##GATKCommandLine=<ID=FilterLiftedVariants,....

When this is parsed by the VCFHeader class, both lines  are fed into the meta data object as follows: (VCFHeader.java: 279)

    mOtherMetaData.put(line.getKey(), line);

And the second entry overwrites the first, so the first line is lost from the meta-data.

Is there supposed to a restriction on the number of elements with the same key allowed in the VCF format?

**Comment by vdauwera** [comment] 2015-03-30 15:52
We are going to fix the GATK VCF header writer to make those lines easier to handle in the next version. Alex will propose some clarifications for the spec.

**Comment by abaumann** [comment] 2015-03-31 21:52
GATK will be fixed in a subsequent release to make unique keys for each GATKCommandLine run rather than using a single key.  This will fix the issue you noticed in VCFHeader.java.    

According to the VCF spec, the meta-information lines are key=value pairs, so in reality you can only have a key once if a parser treats these values as key/value pairs.  INFO, FORMAT, and FILTER are exceptions to the rule that have part of their "keys" on the value side (ID=..., etc).  VCFHeader.java handles the INFO, FORMAT, and FILTER lines separately from all others such that unique keys are extracted to avoid the problem you mentioned, however all other lines' keys will be assumed to be unique.  

I will propose a change to the spec to clarify the special cases for INFO, FORMAT, and FILTER and hopefully avoid confusion in the future over meta-info lines.

**Comment by pd3** [comment] 2015-04-23 12:02
Hi, sorry for my late response, I missed this thread. The VCF specification does allow multiple keys, for example, this is valid:

     ##comment=This is a comment line..
     ##comment=.. and here is another one
     ##comment=.. and all are valid

**Comment by vdauwera** [comment] 2015-04-23 13:11
@pd3 Thanks for your comment. We're aware that this is possible, the problem is that when downstream tools parse this it can cause some difficulties depending on the purpose of the information in those lines, which is what @abaumann was referring to in 

> in reality you can only have a key once if a parser treats these values as key/value pairs

We've handled the problem in the GATK use case but we believe some clarifications in the spec (esp. regarding the potential pitfalls for parsing) may be helpful.

**Comment by vdauwera** [comment] 2015-04-26 21:27
@evolvedmicrobe I'm closing this on the assumption that the GATK fix and Alex's proposed clarification are satisfactory, but let me know if you feel there is something else needed to address this.

**Closed by vdauwera** 2015-04-26 21:27 UTC
Labels: 3 - Done, bug

**Comment by evolvedmicrobe** [comment] 2015-04-26 22:28
@vdauwera Thanks for following up on this!  It looks like the GATK fix resolves the problem just fine by maintaining that information through parse/write cycles, thanks!
