### ISSUE TITLE
IndexFactory.createTabixIndex() not working for .vcf.gz files?

### ISSUE THREAD

**Issue by bbimber** [samtools/htsjdk#210] opened 2015-03-26 18:36 UTC
I find that calls to IndexFactory.createTabixIndex() are consistently failing for VCF files with an error along the lines of "ERROR: Your input file has a malformed header: We never saw the required CHROM header line (starting with one #) for the input VCF file".  I was trying to see where this might be going wrong.  Should IndexFactory.initStream() account for the potential of GZ input files?

**Comment by jmthibault79** [comment] 2015-03-26 19:20
Duplicate of #184

**Closed by jmthibault79** 2015-03-26 19:20 UTC
